#!/usr/bin/perl

use 5.006;
use strict;
use lib qw( blib/lib lib );
use Archive::Zip;
use FileHandle;

use vars qw( $VERSION );
BEGIN {
    $VERSION = '1.51';
}

my $src = "../ColdOMeter/Debug/ColdOMeter.bin";

if (scalar(@ARGV) == 1) {
    $src = $ARGV[0];
}

system("cp $src public/firmware.bin");

my $file = 'public/firmware.bin';

my $fh = FileHandle->new();
if ( !$fh->open( $file, 'r' ) ) {
    warn "$0: $!\n";
    next;
}
binmode($fh);
my $buffer;

my $bytesRead;
my $total = 0;
my $crc = 0;
while ( $bytesRead = $fh->read( $buffer, 32768 ) ) {
    $crc = Archive::Zip::computeCRC32( $buffer, $crc );
    $total += $bytesRead;
}
my $fileCrc = sprintf("%d", $crc);
my $fileLen = sprintf("%d", $total);
open(my $oh, ">", "public/firmware.bin.metadata") or die("Can't open metadata file");
printf $oh "{\n  \"crc32\": $fileCrc,\n  \"length\": $fileLen\n}\n";
close($oh);


